@echo off
echo Starting all microservices...

echo Starting API Gateway (Port 8000)...
start "API Gateway" cmd /k "cd microservices\api-gateway && python src\main.py"

echo Starting EDC Service (Port 8001)...
start "EDC Service" cmd /k "cd microservices\edc-service && python src\main.py"

echo Starting Data Generation Service (Port 8002)...
start "Data Generation Service" cmd /k "cd microservices\data-generation-service && python src\main.py"

echo Starting Analytics Service (Port 8003)...
start "Analytics Service" cmd /k "cd microservices\analytics-service && python src\main.py"

echo Starting Quality Service (Port 8004)...
start "Quality Service" cmd /k "cd microservices\quality-service && python src\main.py"

echo Starting Security Service (Port 8005)...
start "Security Service" cmd /k "cd microservices\security-service && python src\main.py"

echo Starting Daft Analytics Service (Port 8007)...
start "Daft Analytics Service" cmd /k "cd microservices\daft-analytics-service && python src\main.py"

echo Starting Linkup Integration Service (Port 8008)...
start "Linkup Integration Service" cmd /k "cd microservices\linkup-integration-service && python src\main.py"

echo Starting GAIN Service (Port 8009)...
start "GAIN Service" cmd /k "cd microservices\gain-service && python src\main.py"

echo Starting GAN Service (Port 8010)...
start "GAN Service" cmd /k "cd microservices\gan-service && python src\main.py"

echo Starting AI Monitor Service (Port 8011)...
start "AI Monitor Service" cmd /k "cd microservices\ai-monitor-service && python src\main.py"

echo All services started. Please check the individual windows for status.
pause
